# Generated by Django 5.1.4 on 2025-01-15 19:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genome",
            fields=[
                (
                    "genome_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "genome_sequence",
                    models.TextField(
                        validators=[
                            django.core.validators.RegexValidator(
                                message="La séquence doit être uniquement composée des caractères ACGT ou U.",
                                regex="^[ACGTU]*$",
                            )
                        ]
                    ),
                ),
                (
                    "genome_type",
                    models.CharField(
                        choices=[("DNA", "ADN"), ("RNA", "ARN")], max_length=3
                    ),
                ),
                ("organism", models.CharField(max_length=20)),
                ("is_annotated", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "sequence_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("dna_sequence", models.TextField()),
                ("aa_sequence", models.TextField()),
                ("num_chromosome", models.IntegerField()),
                ("sequence_start", models.IntegerField()),
                ("sequence_stop", models.IntegerField()),
                ("sequence_length", models.IntegerField()),
                ("gene_name", models.CharField(max_length=20)),
                (
                    "sequence_status",
                    models.CharField(
                        choices=[
                            ("Nothing", "Non-annotée"),
                            ("Assigned", "Attribuée"),
                            ("Awaiting validation", "En attente de validation"),
                            ("Validated", "Validée"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "genome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequences",
                        to="core.genome",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Domaine",
            fields=[
                (
                    "domain_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("domain_name", models.CharField(max_length=20)),
                ("domain_start", models.IntegerField()),
                ("domain_stop", models.IntegerField()),
                ("domain_length", models.IntegerField()),
                ("domain_function", models.CharField(max_length=50)),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domaines",
                        to="core.sequence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "annotation_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("annotation_text", models.TextField()),
                ("annotation_author", models.CharField(max_length=50)),
                (
                    "sequence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation",
                        to="core.sequence",
                    ),
                ),
            ],
        ),
    ]
