# Generated by Django 5.1.4 on 2025-01-16 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genome",
            name="genome_sequence",
            field=models.TextField(
                validators=[
                    django.core.validators.RegexValidator(
                        message="La séquence doit être composée uniquement des caractères ACGTURYKMSWBDHVN (norme IUPAC).",
                        regex="^[ACGTURYKMSWBDHVN]*$",
                    )
                ]
            ),
        ),
    ]
