# Generated by Django 5.1.5 on 2025-02-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_annotation_is_validated_annotation_rejected_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='peptide_product',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='gene_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
