# Generated by Django 5.1.4 on 2025-02-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_genome_genome_sequence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sequence",
            name="num_chromosome",
        ),
        migrations.AddField(
            model_name="sequence",
            name="information_support",
            field=models.CharField(
                choices=[("Chromosome", "Chromosome"), ("Plasmide", "Plasmide")],
                default="Chromosome",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
