# Generated by Django 5.1.4 on 2025-01-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_connectionhistory_delete_connexionhistorique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("lecteur", "Lecteur"),
                    ("annotateur", "Annotateur"),
                    ("validateur", "Validateur"),
                    ("visiteur", "Visiteur"),
                ],
                default="lecteur",
                max_length=20,
            ),
        ),
    ]
