# Generated by Django 5.1.4 on 2025-02-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sequence_peptide_product_alter_sequence_gene_name"),
        ("core", "0004_alter_customuser_role"),
    ]

    operations = []
