# Generated by Django 5.1.5 on 2025-02-04 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20250203_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionhistory',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
